ALTER TABLE requests MODIFY order_id INT(11) UNSIGNED NOT NULL COMMENT 'id заказа';

ALTER TABLE requests
  ADD CONSTRAINT fk_request_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE loans
  ADD CONSTRAINT fk_loan_mfi FOREIGN KEY (mfi_id) REFERENCES mfi (id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE mfi_responses MODIFY mfi_id INT(11) UNSIGNED NOT NULL COMMENT 'id МФО';
ALTER TABLE mfi_responses MODIFY request_id INT(11) UNSIGNED NOT NULL COMMENT 'id заявки';

ALTER TABLE mfi_responses
  ADD CONSTRAINT fk_mfi_response_mfi FOREIGN KEY (mfi_id) REFERENCES mfi (id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE mfi_responses
  ADD CONSTRAINT fk_mfi_response_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE RESTRICT ON UPDATE CASCADE;
